# Generated by Django 5.1.6 on 2025-03-04 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.FloatField()),
                ('avg_discount', models.FloatField()),
                ('best_selling_product', models.CharField(max_length=255)),
                ('most_profitable_product', models.CharField(max_length=255)),
                ('max_discount_product', models.CharField(max_length=255)),
                ('csv_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processed_data', to='csvapp.csvfile')),
            ],
        ),
    ]
